#!/usr/bin/env node
import fs from 'node:fs';import path from 'node:path';
const a=process.argv.slice(2);const arg=(n,d)=>{const i=a.indexOf(n);return i>=0?a[i+1]:d};const has=n=>a.includes(n);
const root=path.resolve(arg('--root',process.cwd()));const allow=has('--allow-partial');const p=r=>path.join(root,r);const ex=r=>fs.existsSync(p(r));const read=r=>JSON.parse(fs.readFileSync(p(r),'utf8'));
const req=['config/prisma-visual-os/prisma-visual-controls.active.json','styles/prisma-visual-os/prisma-visual-layers.css','styles/prisma-visual-os/prisma-visual-controls.generated.css','docs/design/PRISMA_VISUAL_OS_00D_00E_CONTRACT.md'];
const files=['products/shared-ui/prisma/visual-os/prisma-visual-os.controls.json','products/shared-ui/prisma/visual-os/prisma-visual-os.presets.json','products/shared-ui/prisma/visual-os/prisma-visual-os.recipes.json','products/shared-ui/prisma/visual-os/prisma-visual-os.scorecard.json','products/shared-ui/prisma/visual-os/prisma-visual-os.qa-matrix.00l.json','products/shared-ui/prisma/visual-os/prisma-visual-os.variant-packs.00m.json','products/shared-ui/prisma/visual-os/prisma-visual-os.release-gate.00n.json','docs/design/PRISMA_VISUAL_OS_QA_RELEASE_GATE_00L_00M_00N.md','manifests/PRISMA_VISUAL_QA_RELEASE_GATE_00L_00M_00N_20260503_v01.json','tools/prisma-visual-os/verify_prisma_visual_qa_release_gate_00l_00m_00n.mjs','tools/prisma-visual-os/run_prisma_visual_cross_surface_qa_00l.mjs','tools/prisma-visual-os/print_prisma_visual_variant_packs_00m.mjs','tools/prisma-visual-os/gate_prisma_visual_release_00n.mjs'];
const miss=files.filter(x=>!ex(x));if(miss.length){console.error('[VOS FAIL] missing installed '+miss.join(', '));process.exit(1)}
let controls,presets,qa,variants,gate;try{controls=read(files[0]);presets=read(files[1]);qa=read(files[4]);variants=read(files[5]);gate=read(files[6]);}catch(e){console.error('[VOS FAIL] '+e.message);process.exit(1)}
const presetNames=new Set(Object.keys(presets.presets||{}));if((controls.controls||[]).length<12){console.error('[VOS FAIL] controls too few');process.exit(1)}
for(const s of ['tablet','pc','mobile']){const v=qa.surfaces?.[s];if(!v||!v.expected_recipe||(v.must_not||[]).length<3){console.error('[VOS FAIL] bad qa surface '+s);process.exit(1)}}
for(const [id,pack] of Object.entries(variants.packs||{})){if(!presetNames.has(pack.primaryPreset)){console.error(`[VOS FAIL] ${id} missing preset ${pack.primaryPreset}`);process.exit(1)}if((pack.guardrails||[]).length<2){console.error('[VOS FAIL] weak guardrails '+id);process.exit(1)}}
if(Object.keys(variants.packs||{}).length<5 || (gate.releaseChecks||[]).length<5){console.error('[VOS FAIL] gate or variants incomplete');process.exit(1)}
const missing=req.filter(x=>!ex(x));if(missing.length){for(const x of missing) console.error('[VOS BLOCKED_DEPENDENCY] missing '+x);console.log('[VOS PARTIAL] 00L/00M/00N payload valid; waiting for Chat A 00D/00E.');process.exit(allow?0:3)}
console.log('[VOS OK] 00L/00M/00N verified');process.exit(0);
