export const i11PageData = {
  "summaryCards": [
    {
      "label": "Forecast 14d",
      "value": "115,990 uds",
      "tone": "sky"
    },
    {
      "label": "Compra sugerida",
      "value": "69,641 uds",
      "tone": "amber"
    },
    {
      "label": "SKUs críticos",
      "value": "34",
      "tone": "rose"
    },
    {
      "label": "Proveedores en rojo",
      "value": "5",
      "tone": "violet"
    }
  ],
  "forecastTop": [
    {
      "sku": "SKU-00700",
      "name": "Bebidas producto 700",
      "category": "Bebidas",
      "dailyRunRate": 8.0,
      "forecast7d": 56.0,
      "forecast14d": 112.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 136,
      "grossMarginMx": 1191.68,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 17,
      "stockoutNow": true
    },
    {
      "sku": "SKU-02240",
      "name": "Bebidas producto 2240",
      "category": "Bebidas",
      "dailyRunRate": 8.0,
      "forecast7d": 56.0,
      "forecast14d": 112.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 136,
      "grossMarginMx": 828.8,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-03780",
      "name": "Bebidas producto 3780",
      "category": "Bebidas",
      "dailyRunRate": 8.0,
      "forecast7d": 56.0,
      "forecast14d": 112.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 136,
      "grossMarginMx": 466.48,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-00140",
      "name": "Bebidas producto 140",
      "category": "Bebidas",
      "dailyRunRate": 7.57,
      "forecast7d": 53.0,
      "forecast14d": 106.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 129,
      "grossMarginMx": 1005.41,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 17,
      "stockoutNow": true
    },
    {
      "sku": "SKU-04760",
      "name": "Bebidas producto 4760",
      "category": "Bebidas",
      "dailyRunRate": 7.57,
      "forecast7d": 53.0,
      "forecast14d": 106.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 129,
      "grossMarginMx": 882.45,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-01680",
      "name": "Bebidas producto 1680",
      "category": "Bebidas",
      "dailyRunRate": 7.57,
      "forecast7d": 53.0,
      "forecast14d": 106.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 129,
      "grossMarginMx": 661.97,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-03220",
      "name": "Bebidas producto 3220",
      "category": "Bebidas",
      "dailyRunRate": 7.57,
      "forecast7d": 53.0,
      "forecast14d": 106.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 129,
      "grossMarginMx": 319.06,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-04060",
      "name": "Bebidas producto 4060",
      "category": "Bebidas",
      "dailyRunRate": 7.43,
      "forecast7d": 52.0,
      "forecast14d": 104.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 127,
      "grossMarginMx": 938.08,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-00980",
      "name": "Bebidas producto 980",
      "category": "Bebidas",
      "dailyRunRate": 7.43,
      "forecast7d": 52.0,
      "forecast14d": 104.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 127,
      "grossMarginMx": 721.76,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-02520",
      "name": "Bebidas producto 2520",
      "category": "Bebidas",
      "dailyRunRate": 7.43,
      "forecast7d": 52.0,
      "forecast14d": 104.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 127,
      "grossMarginMx": 384.8,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": 15,
      "stockoutNow": true
    },
    {
      "sku": "SKU-02660",
      "name": "Bebidas producto 2660",
      "category": "Bebidas",
      "dailyRunRate": 7.14,
      "forecast7d": 50.0,
      "forecast14d": 100.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 122,
      "grossMarginMx": 1041.0,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": 15,
      "stockoutNow": true
    },
    {
      "sku": "SKU-04200",
      "name": "Bebidas producto 4200",
      "category": "Bebidas",
      "dailyRunRate": 7.14,
      "forecast7d": 50.0,
      "forecast14d": 100.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 122,
      "grossMarginMx": 717.0,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-01120",
      "name": "Bebidas producto 1120",
      "category": "Bebidas",
      "dailyRunRate": 7.14,
      "forecast7d": 50.0,
      "forecast14d": 100.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 122,
      "grossMarginMx": 509.0,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-01960",
      "name": "Bebidas producto 1960",
      "category": "Bebidas",
      "dailyRunRate": 7.0,
      "forecast7d": 49.0,
      "forecast14d": 98.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 119,
      "grossMarginMx": 1087.8,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-03500",
      "name": "Bebidas producto 3500",
      "category": "Bebidas",
      "dailyRunRate": 7.0,
      "forecast7d": 49.0,
      "forecast14d": 98.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 119,
      "grossMarginMx": 770.77,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-00420",
      "name": "Bebidas producto 420",
      "category": "Bebidas",
      "dailyRunRate": 7.0,
      "forecast7d": 49.0,
      "forecast14d": 98.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 119,
      "grossMarginMx": 566.93,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 17,
      "stockoutNow": true
    },
    {
      "sku": "SKU-02800",
      "name": "Bebidas producto 2800",
      "category": "Bebidas",
      "dailyRunRate": 6.86,
      "forecast7d": 48.0,
      "forecast14d": 96.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 117,
      "grossMarginMx": 821.76,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": 15,
      "stockoutNow": true
    },
    {
      "sku": "SKU-04340",
      "name": "Bebidas producto 4340",
      "category": "Bebidas",
      "dailyRunRate": 6.86,
      "forecast7d": 48.0,
      "forecast14d": 96.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 117,
      "grossMarginMx": 510.72,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-01260",
      "name": "Bebidas producto 1260",
      "category": "Bebidas",
      "dailyRunRate": 6.86,
      "forecast7d": 48.0,
      "forecast14d": 96.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 117,
      "grossMarginMx": 311.04,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-02100",
      "name": "Bebidas producto 2100",
      "category": "Bebidas",
      "dailyRunRate": 6.71,
      "forecast7d": 47.0,
      "forecast14d": 94.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 115,
      "grossMarginMx": 869.5,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-03640",
      "name": "Bebidas producto 3640",
      "category": "Bebidas",
      "dailyRunRate": 6.71,
      "forecast7d": 47.0,
      "forecast14d": 94.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 115,
      "grossMarginMx": 565.41,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": null,
      "stockoutNow": true
    },
    {
      "sku": "SKU-00560",
      "name": "Bebidas producto 560",
      "category": "Bebidas",
      "dailyRunRate": 6.71,
      "forecast7d": 47.0,
      "forecast14d": 94.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 115,
      "grossMarginMx": 369.89,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 17,
      "stockoutNow": true
    },
    {
      "sku": "SKU-01400",
      "name": "Bebidas producto 1400",
      "category": "Bebidas",
      "dailyRunRate": 6.57,
      "forecast7d": 46.0,
      "forecast14d": 92.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 112,
      "grossMarginMx": 914.94,
      "marginPctCategory": 37.01,
      "priority": "high",
      "risk": "critico",
      "priceAgeDays": 16,
      "stockoutNow": true
    },
    {
      "sku": "SKU-02940",
      "name": "Bebidas producto 2940",
      "category": "Bebidas",
      "dailyRunRate": 6.57,
      "forecast7d": 46.0,
      "forecast14d": 92.0,
      "availableProxy": 0,
      "daysCover": 0.0,
      "suggestedBuyQty": 112,
      "grossMarginMx": 617.32,
      "marginPctCategory": 37.01,
      "priority": "critico",
      "risk": "critico",
      "priceAgeDays": 15,
      "stockoutNow": true
    }
  ],
  "alertsTop": [
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-00700",
      "title": "SKU-00700 sin inventario con demanda activa",
      "detail": "Bebidas producto 700 proyecta 56.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 56.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-02240",
      "title": "SKU-02240 sin inventario con demanda activa",
      "detail": "Bebidas producto 2240 proyecta 56.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 56.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-03780",
      "title": "SKU-03780 sin inventario con demanda activa",
      "detail": "Bebidas producto 3780 proyecta 56.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 56.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-00140",
      "title": "SKU-00140 sin inventario con demanda activa",
      "detail": "Bebidas producto 140 proyecta 53.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 53.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-04760",
      "title": "SKU-04760 sin inventario con demanda activa",
      "detail": "Bebidas producto 4760 proyecta 53.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 53.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-01680",
      "title": "SKU-01680 sin inventario con demanda activa",
      "detail": "Bebidas producto 1680 proyecta 53.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 53.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-03220",
      "title": "SKU-03220 sin inventario con demanda activa",
      "detail": "Bebidas producto 3220 proyecta 53.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 53.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-04060",
      "title": "SKU-04060 sin inventario con demanda activa",
      "detail": "Bebidas producto 4060 proyecta 52.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 52.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-00980",
      "title": "SKU-00980 sin inventario con demanda activa",
      "detail": "Bebidas producto 980 proyecta 52.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 52.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-02520",
      "title": "SKU-02520 sin inventario con demanda activa",
      "detail": "Bebidas producto 2520 proyecta 52.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 52.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-02660",
      "title": "SKU-02660 sin inventario con demanda activa",
      "detail": "Bebidas producto 2660 proyecta 50.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 50.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-04200",
      "title": "SKU-04200 sin inventario con demanda activa",
      "detail": "Bebidas producto 4200 proyecta 50.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 50.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-01120",
      "title": "SKU-01120 sin inventario con demanda activa",
      "detail": "Bebidas producto 1120 proyecta 50.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 50.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-01960",
      "title": "SKU-01960 sin inventario con demanda activa",
      "detail": "Bebidas producto 1960 proyecta 49.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 49.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-03500",
      "title": "SKU-03500 sin inventario con demanda activa",
      "detail": "Bebidas producto 3500 proyecta 49.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 49.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-00420",
      "title": "SKU-00420 sin inventario con demanda activa",
      "detail": "Bebidas producto 420 proyecta 49.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 49.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-02800",
      "title": "SKU-02800 sin inventario con demanda activa",
      "detail": "Bebidas producto 2800 proyecta 48.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 48.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-04340",
      "title": "SKU-04340 sin inventario con demanda activa",
      "detail": "Bebidas producto 4340 proyecta 48.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 48.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-01260",
      "title": "SKU-01260 sin inventario con demanda activa",
      "detail": "Bebidas producto 1260 proyecta 48.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 48.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-02100",
      "title": "SKU-02100 sin inventario con demanda activa",
      "detail": "Bebidas producto 2100 proyecta 47.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 47.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-03640",
      "title": "SKU-03640 sin inventario con demanda activa",
      "detail": "Bebidas producto 3640 proyecta 47.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 47.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-00560",
      "title": "SKU-00560 sin inventario con demanda activa",
      "detail": "Bebidas producto 560 proyecta 47.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 47.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-01400",
      "title": "SKU-01400 sin inventario con demanda activa",
      "detail": "Bebidas producto 1400 proyecta 46.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 46.0
    },
    {
      "area": "inventario",
      "type": "stockout_en_demanda",
      "severity": "critica",
      "entity": "SKU-02940",
      "title": "SKU-02940 sin inventario con demanda activa",
      "detail": "Bebidas producto 2940 proyecta 46.0 uds en 7d y está en cero.",
      "owner": "stock",
      "action": "revisar compra o reabasto inmediato",
      "metric": 46.0
    }
  ],
  "supplierScorecards": [
    {
      "supplier": "Farmacia Barrial",
      "totalOrders": 140,
      "receivedOrders": 46,
      "partialOrders": 47,
      "servicePct": 32.86,
      "partialPct": 33.57,
      "incidentReceiptPct": 25.0,
      "lineFillPct": 0.0,
      "pendingQty": 2400,
      "lineValueMx": 431267.83,
      "healthBand": "rojo"
    },
    {
      "supplier": "Snacks MX",
      "totalOrders": 140,
      "receivedOrders": 46,
      "partialOrders": 47,
      "servicePct": 32.86,
      "partialPct": 33.57,
      "incidentReceiptPct": 25.0,
      "lineFillPct": 0.0,
      "pendingQty": 9600,
      "lineValueMx": 432293.09,
      "healthBand": "rojo"
    },
    {
      "supplier": "Bebidas del Centro",
      "totalOrders": 140,
      "receivedOrders": 47,
      "partialOrders": 46,
      "servicePct": 33.57,
      "partialPct": 32.86,
      "incidentReceiptPct": 25.0,
      "lineFillPct": 0.0,
      "pendingQty": 0,
      "lineValueMx": 431305.05,
      "healthBand": "rojo"
    },
    {
      "supplier": "Limpieza Uno",
      "totalOrders": 140,
      "receivedOrders": 47,
      "partialOrders": 46,
      "servicePct": 33.57,
      "partialPct": 32.86,
      "incidentReceiptPct": 25.0,
      "lineFillPct": 0.0,
      "pendingQty": 4800,
      "lineValueMx": 431809.98,
      "healthBand": "rojo"
    },
    {
      "supplier": "Lácteos del Norte",
      "totalOrders": 140,
      "receivedOrders": 47,
      "partialOrders": 47,
      "servicePct": 33.57,
      "partialPct": 33.57,
      "incidentReceiptPct": 25.0,
      "lineFillPct": 100.0,
      "pendingQty": 7200,
      "lineValueMx": 431273.85,
      "healthBand": "rojo"
    }
  ],
  "categoryScorecards": [
    {
      "category": "Bebidas",
      "skuCount": 241,
      "forecast7d": 11644.0,
      "forecast14d": 23288.0,
      "suggestedBuyQty": 17491,
      "grossMarginMx": 162827.52,
      "avgMarginPct": 37.01,
      "avgPriceMx": 37.48,
      "criticalSkus": 34,
      "highRiskSkus": 134,
      "stockoutNow": 34,
      "stalePriceSkus": 142,
      "healthBand": "rojo"
    },
    {
      "category": "Limpieza",
      "skuCount": 242,
      "forecast7d": 11676.0,
      "forecast14d": 23352.0,
      "suggestedBuyQty": 13218,
      "grossMarginMx": 163543.95,
      "avgMarginPct": 37.01,
      "avgPriceMx": 37.48,
      "criticalSkus": 0,
      "highRiskSkus": 0,
      "stockoutNow": 0,
      "stalePriceSkus": 144,
      "healthBand": "verde"
    },
    {
      "category": "Farmacia",
      "skuCount": 241,
      "forecast7d": 11639.0,
      "forecast14d": 23278.0,
      "suggestedBuyQty": 13194,
      "grossMarginMx": 162996.98,
      "avgMarginPct": 37.01,
      "avgPriceMx": 37.48,
      "criticalSkus": 0,
      "highRiskSkus": 0,
      "stockoutNow": 0,
      "stalePriceSkus": 147,
      "healthBand": "verde"
    },
    {
      "category": "Lácteos",
      "skuCount": 238,
      "forecast7d": 11522.0,
      "forecast14d": 23044.0,
      "suggestedBuyQty": 12957,
      "grossMarginMx": 162928.49,
      "avgMarginPct": 37.01,
      "avgPriceMx": 37.48,
      "criticalSkus": 0,
      "highRiskSkus": 0,
      "stockoutNow": 0,
      "stalePriceSkus": 146,
      "healthBand": "verde"
    },
    {
      "category": "Snacks",
      "skuCount": 238,
      "forecast7d": 11514.0,
      "forecast14d": 23028.0,
      "suggestedBuyQty": 12781,
      "grossMarginMx": 161789.36,
      "avgMarginPct": 37.01,
      "avgPriceMx": 37.48,
      "criticalSkus": 0,
      "highRiskSkus": 0,
      "stockoutNow": 0,
      "stalePriceSkus": 142,
      "healthBand": "verde"
    }
  ]
} as const;
