graph TD
	QHZT("@hitech/ai-agent#build") --> ETTT("___ROOT___")
	JEGP("@hitech/contracts#build") --> ETTT("___ROOT___")
	EMLE("@hitech/core-api#build") --> ETTT("___ROOT___")
	LRHC("@hitech/demo-engine#build") --> ETTT("___ROOT___")
	GLAO("@hitech/health#build") --> ETTT("___ROOT___")
	VELR("@hitech/keystone#build") --> JEGP("@hitech/contracts#build")
	VELR("@hitech/keystone#build") --> TXWC("@hitech/ui-kit#build")
	WCIN("@hitech/scripts#build") --> ETTT("___ROOT___")
	TPBW("@hitech/tooling#build") --> ETTT("___ROOT___")
	TXWC("@hitech/ui-kit#build") --> ETTT("___ROOT___")
	BHWE("@hitech/web#build") --> JEGP("@hitech/contracts#build")
	BHWE("@hitech/web#build") --> TXWC("@hitech/ui-kit#build")
