from __future__ import annotations

from importlib import import_module

CASE_MODULE_NAMES = [
    'fixtures_py.case_001_payments_console',
    'fixtures_py.case_002_telemetry_hub',
    'fixtures_py.case_003_route_compass',
    'fixtures_py.case_004_inventory_orbit',
    'fixtures_py.case_005_policy_registry',
    'fixtures_py.case_006_signal_forge',
    'fixtures_py.case_007_desktop_bridge',
    'fixtures_py.case_008_module_radar',
    'fixtures_py.case_009_tenant_mapper',
    'fixtures_py.case_010_latency_watch',
    'fixtures_py.case_011_revenue_graph',
    'fixtures_py.case_012_audit_canvas',
    'fixtures_py.case_013_session_courier',
    'fixtures_py.case_014_fraud_lantern',
    'fixtures_py.case_015_ops_telescope',
    'fixtures_py.case_016_supply_grid',
    'fixtures_py.case_017_parcel_switch',
    'fixtures_py.case_018_quote_foundry',
    'fixtures_py.case_019_claims_orbit',
    'fixtures_py.case_020_profile_atlas',
    'fixtures_py.case_021_checkout_reef',
    'fixtures_py.case_022_billing_meadow',
    'fixtures_py.case_023_support_vector',
    'fixtures_py.case_024_shipment_lens',
    'fixtures_py.case_025_identity_pulse',
    'fixtures_py.case_026_pricing_wharf',
    'fixtures_py.case_027_forecast_bloom',
    'fixtures_py.case_028_ledger_tunnel',
    'fixtures_py.case_029_entitlement_clinic',
    'fixtures_py.case_030_consent_harbor',
    'fixtures_py.case_031_payments_console',
    'fixtures_py.case_032_telemetry_hub',
    'fixtures_py.case_033_route_compass',
    'fixtures_py.case_034_inventory_orbit',
    'fixtures_py.case_035_policy_registry',
    'fixtures_py.case_036_signal_forge',
    'fixtures_py.case_037_desktop_bridge',
    'fixtures_py.case_038_module_radar',
    'fixtures_py.case_039_tenant_mapper',
    'fixtures_py.case_040_latency_watch',
    'fixtures_py.case_041_revenue_graph',
    'fixtures_py.case_042_audit_canvas',
    'fixtures_py.case_043_session_courier',
    'fixtures_py.case_044_fraud_lantern',
    'fixtures_py.case_045_ops_telescope',
    'fixtures_py.case_046_supply_grid',
    'fixtures_py.case_047_parcel_switch',
    'fixtures_py.case_048_quote_foundry',
    'fixtures_py.case_049_claims_orbit',
    'fixtures_py.case_050_profile_atlas',
    'fixtures_py.case_051_checkout_reef',
    'fixtures_py.case_052_billing_meadow',
    'fixtures_py.case_053_support_vector',
    'fixtures_py.case_054_shipment_lens',
    'fixtures_py.case_055_identity_pulse',
    'fixtures_py.case_056_pricing_wharf',
    'fixtures_py.case_057_forecast_bloom',
    'fixtures_py.case_058_ledger_tunnel',
    'fixtures_py.case_059_entitlement_clinic',
    'fixtures_py.case_060_consent_harbor',
    'fixtures_py.case_061_payments_console',
    'fixtures_py.case_062_telemetry_hub',
    'fixtures_py.case_063_route_compass',
    'fixtures_py.case_064_inventory_orbit',
    'fixtures_py.case_065_policy_registry',
    'fixtures_py.case_066_signal_forge',
    'fixtures_py.case_067_desktop_bridge',
    'fixtures_py.case_068_module_radar',
    'fixtures_py.case_069_tenant_mapper',
    'fixtures_py.case_070_latency_watch',
    'fixtures_py.case_071_revenue_graph',
    'fixtures_py.case_072_audit_canvas',
    'fixtures_py.case_073_session_courier',
    'fixtures_py.case_074_fraud_lantern',
    'fixtures_py.case_075_ops_telescope',
    'fixtures_py.case_076_supply_grid',
    'fixtures_py.case_077_parcel_switch',
    'fixtures_py.case_078_quote_foundry',
    'fixtures_py.case_079_claims_orbit',
    'fixtures_py.case_080_profile_atlas',
    'fixtures_py.case_081_checkout_reef',
    'fixtures_py.case_082_billing_meadow',
    'fixtures_py.case_083_support_vector',
    'fixtures_py.case_084_shipment_lens',
    'fixtures_py.case_085_identity_pulse',
    'fixtures_py.case_086_pricing_wharf',
    'fixtures_py.case_087_forecast_bloom',
    'fixtures_py.case_088_ledger_tunnel',
    'fixtures_py.case_089_entitlement_clinic',
    'fixtures_py.case_090_consent_harbor',
    'fixtures_py.case_091_payments_console',
    'fixtures_py.case_092_telemetry_hub',
    'fixtures_py.case_093_route_compass',
    'fixtures_py.case_094_inventory_orbit',
    'fixtures_py.case_095_policy_registry',
    'fixtures_py.case_096_signal_forge',
    'fixtures_py.case_097_desktop_bridge',
    'fixtures_py.case_098_module_radar',
    'fixtures_py.case_099_tenant_mapper',
    'fixtures_py.case_100_latency_watch',
    'fixtures_py.case_101_revenue_graph',
    'fixtures_py.case_102_audit_canvas',
    'fixtures_py.case_103_session_courier',
    'fixtures_py.case_104_fraud_lantern',
    'fixtures_py.case_105_ops_telescope',
    'fixtures_py.case_106_supply_grid',
    'fixtures_py.case_107_parcel_switch',
    'fixtures_py.case_108_quote_foundry',
    'fixtures_py.case_109_claims_orbit',
    'fixtures_py.case_110_profile_atlas',
    'fixtures_py.case_111_checkout_reef',
    'fixtures_py.case_112_billing_meadow',
    'fixtures_py.case_113_support_vector',
    'fixtures_py.case_114_shipment_lens',
    'fixtures_py.case_115_identity_pulse',
    'fixtures_py.case_116_pricing_wharf',
    'fixtures_py.case_117_forecast_bloom',
    'fixtures_py.case_118_ledger_tunnel',
    'fixtures_py.case_119_entitlement_clinic',
    'fixtures_py.case_120_consent_harbor',
    'fixtures_py.case_121_payments_console',
    'fixtures_py.case_122_telemetry_hub',
    'fixtures_py.case_123_route_compass',
    'fixtures_py.case_124_inventory_orbit',
    'fixtures_py.case_125_policy_registry',
    'fixtures_py.case_126_signal_forge',
    'fixtures_py.case_127_desktop_bridge',
    'fixtures_py.case_128_module_radar',
]

def iter_cases():
    for name in CASE_MODULE_NAMES:
        yield import_module(name).CASE

def get_case(name: str):
    key = name if name.startswith("fixtures_py.") else f"fixtures_py.{name}"
    return import_module(key).CASE

def selected_verification_cases():
    picks = []
    for idx, case in enumerate(iter_cases(), start=1):
        if idx in {1, 4, 9, 16, 25, 36}:
            picks.append(case)
    return picks

