import fs from "node:fs";
import path from "node:path";
import childProcess from "node:child_process";
const root=process.cwd();const r=x=>fs.readFileSync(path.join(root,x),"utf8");const e=x=>fs.existsSync(path.join(root,x));function a(ok,msg){if(!ok){console.error(`[FAIL] ${msg}`);process.exitCode=1}else console.log(`[OK] ${msg}`)};
const required=["components/pos/pos-screen.tsx","components/pos/pos-payment-panel.tsx","components/pos/pos-sale-success.tsx","components/sales/sales-today-screen.tsx","components/sales/sales-ticket-list.tsx","components/sales/sales-ticket-detail-screen.tsx","components/returns/return-from-ticket-screen.tsx","app/api/pos/returns/create/route.ts","components/tablet-shell/tablet-nav.ts","src/lib/pos/payment-ledger.ts","src/lib/pos/payment-error-normalizer.ts","src/lib/pos/payment-offline-policy.ts","src/lib/sales-today/sales-kpi-engine.ts","src/lib/sales-today/sales-ticket-filters.ts","src/lib/sales-today/sales-ticket-export.ts","src/lib/returns-contextual/return-policy-engine.ts","src/lib/returns-contextual/return-audit-ledger.ts","src/lib/returns-contextual/return-stock-impact.ts","src/server/pos-api/sales-detail.prisma.ts","src/server/pos-api/returns-policy.prisma.ts","components/pos/pos-payment-risk-banner.tsx","components/sales/sales-ticket-status-chip.tsx","components/returns/return-impact-summary.tsx","tools/verify_tablet_payment_sales_returns_regression_03e_03i.mjs","tools/verify_tablet_payment_sales_returns_route_graph_03e_03i.mjs","tools/fixtures/tablet_payment_sales_returns_regression_cases_03e_03i.json","tools/fixtures/tablet_payment_sales_returns_casebook_03e_03i.json","tools/verify_tablet_payment_sales_returns_casebook_03e_03i.mjs","src/lib/pos/payment-operation-events.ts","docs/ops/PRISMA_TABLET_PAYMENT_SALES_RETURNS_FLOW_03E_03I_INSTALL_NOTES.md"];
for(const f of required){a(e(f),`exists ${f}`)}
const all=["components/pos/pos-screen.tsx","components/pos/pos-ticket-panel.tsx","components/pos/pos-payment-panel.tsx","components/pos/pos-sale-success.tsx","components/sales/sales-today-screen.tsx","components/sales/sales-ticket-list.tsx","components/sales/sales-ticket-detail-screen.tsx","components/returns/return-from-ticket-screen.tsx","src/server/pos-api/returns.prisma.ts","src/lib/pos/payment-ledger.ts","src/lib/pos/payment-error-normalizer.ts","src/lib/pos/payment-offline-policy.ts","src/lib/sales-today/sales-kpi-engine.ts","src/lib/returns-contextual/return-policy-engine.ts","src/lib/pos/payment-operation-events.ts"].map(r).join("\n");
for(const token of ["Cobro dentro de Vender","Confirmar venta","Ticket cerrado","Ventas de hoy","Ver detalle","Hacer devolución","Confirmar devolución","sale.return.created","clientRequestId","buildPaymentLedger","normalizePosError","evaluateOfflineSalePolicy","buildSalesTodayKpis","evaluateReturnPolicy","createTabletPaymentEvent","tablet.payment.confirm.completed"]){a(all.includes(token),`contains ${token}`)}
const nav=r("components/tablet-shell/tablet-nav.ts");for(const bad of ["Cobro","Devoluciones","Sincronización","Exportar"]){a(!nav.includes(`label: \"${bad}\"`),`nav excludes ${bad}`)}
for(const bad of ["products/pc/","products/mobile/","shared-kernel","schema.prisma"]){a(!all.includes(bad),`avoids ${bad}`)}
for(const verifier of ["tools/verify_tablet_payment_sales_returns_regression_03e_03i.mjs","tools/verify_tablet_payment_sales_returns_route_graph_03e_03i.mjs","tools/verify_tablet_payment_sales_returns_casebook_03e_03i.mjs"]){const res=childProcess.spawnSync(process.execPath,[path.join(root,verifier)],{cwd:root,encoding:"utf8"});process.stdout.write(res.stdout??"");process.stderr.write(res.stderr??"");a(res.status===0,`${verifier} passes`)}
if(process.exitCode)process.exit(process.exitCode);console.log("[OK] 03E-03I verified")
