import type { Meta, StoryObj } from "@storybook/react";
import { DemoGlassCard } from "./DemoGlassCard";

const meta: Meta<typeof DemoGlassCard> = {
  title: "Generated/DemoGlassCard",
  component: DemoGlassCard,
  args: {
    title: "DemoGlassCard Title",
    subtitle: "Generated by tools/hos/ui/scaffold_component.py"
  }
};

export default meta;
type Story = StoryObj<typeof DemoGlassCard>;

export const Default: Story = {
  render: (args) => (
    <DemoGlassCard {...args}>
      <p>Replace this placeholder content with a real UI fragment.</p>
    </DemoGlassCard>
  )
};
