graph BT
  Z0[Z-0 fondo] --> Z1[Z-1 haze]
  Z1 --> Z2[Z-2 shell]
  Z2 --> Z3[Z-3 sidebar header]
  Z3 --> Z4[Z-4 paneles]
  Z4 --> Z5[Z-5 cards controles]
  Z5 --> Z6[Z-6 stage aura]
  Z6 --> Z7[Z-7 packshot]
  Z7 --> Z8[Z-8 texto precio]
  Z8 --> Z9[Z-9 total cobrar]
  Z9 --> Z10[Z-10 overlays]
