"""Reusable PySide6 glass framework for ForgeOS tools.

Compat facade restored from the pre-modularized API surface.
This bridge keeps package-root imports working while nudging
callers toward explicit module imports.
"""

from __future__ import annotations

from importlib import import_module as _import_module
from ._migration import warn_legacy_root_import as _warn_legacy_root_import

_SYMBOL_TO_MODULE = {
    "FrostedGlassBackdrop": ".backdrop",
    "WindowChromeBar": ".chrome",
    "GlassCatalogEntry": ".catalog",
    "get_catalog_entry": ".catalog",
    "list_catalog_categories": ".catalog",
    "list_catalog_entries": ".catalog",
    "list_catalog_tags": ".catalog",
    "register_builtin_catalog_entries": ".catalog",
    "register_catalog_entry": ".catalog",
    "GlassAccessibilityConfig": ".config",
    "GlassActionConfig": ".config",
    "GlassAnimationConfig": ".config",
    "GlassInteractionConfig": ".config",
    "GlassLayoutConfig": ".config",
    "GlassPersistenceConfig": ".config",
    "GlassRegionConfig": ".config",
    "GlassRegionPolicyConfig": ".config",
    "GlassResolvedConfig": ".config",
    "GlassTabConfig": ".config",
    "GlassTemplateConfig": ".config",
    "GlassThemeConfig": ".config",
    "GlassTypographyConfig": ".config",
    "GlassVisualScaleConfig": ".config",
    "get_template_preset": ".config",
    "list_template_presets": ".config",
    "merge_template_config": ".config",
    "register_template_preset": ".config",
    "resolve_template_config": ".config",
    "resolve_template_config_with_provenance": ".config",
    "GLASS_DENSITY": ".contracts",
    "GLASS_RADIUS": ".contracts",
    "GLASS_SPACING": ".contracts",
    "GLASS_TYPOGRAPHY": ".contracts",
    "PANEL_ROLES": ".contracts",
    "SUPPORTED_ANIMATION_LEVELS": ".contracts",
    "SUPPORTED_DENSITY": ".contracts",
    "SUPPORTED_EXPERIENCE_MODES": ".contracts",
    "SUPPORTED_PANEL_STATES": ".contracts",
    "SUPPORTED_TAB_DENSITY": ".contracts",
    "SUPPORTED_TAB_ICON_MODES": ".contracts",
    "SUPPORTED_TAB_PLACEMENT": ".contracts",
    "SUPPORTED_TAB_STATES": ".contracts",
    "SUPPORTED_TAB_VARIANTS": ".contracts",
    "SUPPORTED_TYPOGRAPHY_SCALE": ".contracts",
    "GlassDensityContract": ".contracts",
    "GlassRadiusContract": ".contracts",
    "GlassSpacingContract": ".contracts",
    "GlassTypographyContract": ".contracts",
    "CollapsibleSection": ".assets",
    "CompactToolbar": ".assets",
    "ControlCard": ".assets",
    "EnhancedSlider": ".assets",
    "FilterChipBar": ".assets",
    "GlassIconButton": ".assets",
    "GlassSegmentedControl": ".assets",
    "HeroPanel": ".assets",
    "MiniLegend": ".assets",
    "ParameterPanel": ".assets",
    "SearchCommandBar": ".assets",
    "StatPill": ".assets",
    "StatusPill": ".assets",
    "TogglePill": ".assets",
    "create_button": ".controls",
    "list_button_variants": ".controls",
    "DashboardDataSurface": ".dashboard",
    "DashboardQuerySpec": ".dashboard",
    "DATA_STATES": ".data",
    "DashboardDataProvider": ".data",
    "DataError": ".data",
    "DataProviderMeta": ".data",
    "DataQuery": ".data",
    "DataResult": ".data",
    "DataState": ".data",
    "FunctionDataProvider": ".data",
    "RefreshPolicy": ".data",
    "data_provider_diagnostics": ".data",
    "describe_data_provider": ".data",
    "execute_data_query": ".data",
    "get_data_provider": ".data",
    "list_data_providers": ".data",
    "register_data_provider": ".data",
    "InMemoryDashboardProvider": ".data_providers",
    "LocalSQLiteDashboardProvider": ".data_providers",
    "default_local_dashboard_db_path": ".data_providers",
    "register_builtin_data_providers": ".data_providers",
    "config_snapshot": ".diagnostics",
    "resolved_snapshot": ".diagnostics",
    "template_runtime_snapshot": ".diagnostics",
    "validate_template_config": ".diagnostics",
    "GlassCapability": ".extensions",
    "GlassExtensionRegistry": ".extensions",
    "extension_registry": ".extensions",
    "list_registered_capabilities": ".extensions",
    "register_capability": ".extensions",
    "register_icon_pack_extension": ".extensions",
    "register_preset_extension": ".extensions",
    "register_theme_extension": ".extensions",
    "register_theme_override_extension": ".extensions",
    "GlassIconPack": ".icons",
    "GlassResolvedIcon": ".icons",
    "apply_icon": ".icons",
    "get_default_icon_namespace": ".icons",
    "get_default_icon_pack": ".icons",
    "get_icon": ".icons",
    "list_icon_packs": ".icons",
    "register_icon_namespace": ".icons",
    "register_icon_pack": ".icons",
    "register_icon_size_token": ".icons",
    "set_default_icon_namespace": ".icons",
    "set_default_icon_pack": ".icons",
    "INTEGRATION_PROTOCOL_VERSION": ".integration",
    "GlassRuntimeIntegrationBridge": ".integration",
    "IpcIntegrationAdapterScaffold": ".integration",
    "InProcessIntegrationAdapter": ".integration",
    "IntegrationClientContext": ".integration",
    "IntegrationCommandEnvelope": ".integration",
    "IntegrationEndpointSpec": ".integration",
    "IntegrationEnvelopeMeta": ".integration",
    "IntegrationError": ".integration",
    "IntegrationEvent": ".integration",
    "IntegrationQueryEnvelope": ".integration",
    "IntegrationResponse": ".integration",
    "IntegrationService": ".integration",
    "IntegrationSnapshotRequest": ".integration",
    "IntegrationValidationError": ".integration",
    "LocalHttpIntegrationAdapter": ".integration",
    "LocalHttpIntegrationConfig": ".integration",
    "ReferenceWorkspaceState": ".integration",
    "WebSocketIntegrationAdapterScaffold": ".integration",
    "create_reference_workspace_service": ".integration",
    "register_reference_workspace_endpoints": ".integration",
    "CURRENT_WORKSPACE_SCHEMA_VERSION": ".persistence",
    "GlassWorkspaceState": ".persistence",
    "load_workspace_state": ".persistence",
    "save_workspace_state": ".persistence",
    "DashboardWidgetShell": ".primitives",
    "EmptyStateCard": ".primitives",
    "ErrorStateCard": ".primitives",
    "FormSectionShell": ".primitives",
    "LoadingStateCard": ".primitives",
    "PanelHeader": ".primitives",
    "QuickActionsStrip": ".primitives",
    "StatCard": ".primitives",
    "GlassRuntimeContext": ".runtime",
    "GlassVisibilityPolicy": ".runtime",
    "GlassVisibilityRule": ".runtime",
    "GlassWorkspaceRuntime": ".runtime",
    "build_glass_dialog_scene": ".scene",
    "GlassLayoutController": ".template",
    "GlassPanelFrame": ".template",
    "GlassPanelSpec": ".template",
    "GlassPanelTemplate": ".template",
    "GlassTemplateActions": ".template",
    "GlassTemplateCards": ".template",
    "GlassTemplateSlots": ".template",
    "GlassWorkspaceTabSpec": ".template",
    "GlassWorkspaceTabs": ".template",
    "DEFAULT_THEME_ID": ".theme",
    "GlassPalette": ".theme",
    "GlassThemeManifest": ".theme",
    "build_stylesheet": ".theme",
    "get_palette": ".theme",
    "get_theme_manifest": ".theme",
    "list_theme_ids": ".theme",
    "register_theme": ".theme",
    "register_theme_overrides": ".theme",
    "AssetCatalogEntrySpec": ".examples",
    "DashboardCatalogEntrySpec": ".examples",
    "GlassCatalogShell": ".examples",
    "build_dashboard_catalog_entry": ".examples",
    "iter_asset_catalog_specs": ".examples",
    "iter_dashboard_catalog_specs": ".examples",
}

__all__ = [
    "FrostedGlassBackdrop",
    "WindowChromeBar",
    "GlassCatalogEntry",
    "get_catalog_entry",
    "list_catalog_categories",
    "list_catalog_entries",
    "list_catalog_tags",
    "register_builtin_catalog_entries",
    "register_catalog_entry",
    "GlassAccessibilityConfig",
    "GlassActionConfig",
    "GlassAnimationConfig",
    "GlassInteractionConfig",
    "GlassLayoutConfig",
    "GlassPersistenceConfig",
    "GlassRegionConfig",
    "GlassRegionPolicyConfig",
    "GlassResolvedConfig",
    "GlassTabConfig",
    "GlassTemplateConfig",
    "GlassThemeConfig",
    "GlassTypographyConfig",
    "GlassVisualScaleConfig",
    "get_template_preset",
    "list_template_presets",
    "merge_template_config",
    "register_template_preset",
    "resolve_template_config",
    "resolve_template_config_with_provenance",
    "GLASS_DENSITY",
    "GLASS_RADIUS",
    "GLASS_SPACING",
    "GLASS_TYPOGRAPHY",
    "PANEL_ROLES",
    "SUPPORTED_ANIMATION_LEVELS",
    "SUPPORTED_DENSITY",
    "SUPPORTED_EXPERIENCE_MODES",
    "SUPPORTED_PANEL_STATES",
    "SUPPORTED_TAB_DENSITY",
    "SUPPORTED_TAB_ICON_MODES",
    "SUPPORTED_TAB_PLACEMENT",
    "SUPPORTED_TAB_STATES",
    "SUPPORTED_TAB_VARIANTS",
    "SUPPORTED_TYPOGRAPHY_SCALE",
    "GlassDensityContract",
    "GlassRadiusContract",
    "GlassSpacingContract",
    "GlassTypographyContract",
    "CollapsibleSection",
    "CompactToolbar",
    "ControlCard",
    "EnhancedSlider",
    "FilterChipBar",
    "GlassIconButton",
    "GlassSegmentedControl",
    "HeroPanel",
    "MiniLegend",
    "ParameterPanel",
    "SearchCommandBar",
    "StatPill",
    "StatusPill",
    "TogglePill",
    "create_button",
    "list_button_variants",
    "DashboardDataSurface",
    "DashboardQuerySpec",
    "DATA_STATES",
    "DashboardDataProvider",
    "DataError",
    "DataProviderMeta",
    "DataQuery",
    "DataResult",
    "DataState",
    "FunctionDataProvider",
    "RefreshPolicy",
    "data_provider_diagnostics",
    "describe_data_provider",
    "execute_data_query",
    "get_data_provider",
    "list_data_providers",
    "register_data_provider",
    "InMemoryDashboardProvider",
    "LocalSQLiteDashboardProvider",
    "default_local_dashboard_db_path",
    "register_builtin_data_providers",
    "config_snapshot",
    "resolved_snapshot",
    "template_runtime_snapshot",
    "validate_template_config",
    "GlassCapability",
    "GlassExtensionRegistry",
    "extension_registry",
    "list_registered_capabilities",
    "register_capability",
    "register_icon_pack_extension",
    "register_preset_extension",
    "register_theme_extension",
    "register_theme_override_extension",
    "GlassIconPack",
    "GlassResolvedIcon",
    "apply_icon",
    "get_default_icon_namespace",
    "get_default_icon_pack",
    "get_icon",
    "list_icon_packs",
    "register_icon_namespace",
    "register_icon_pack",
    "register_icon_size_token",
    "set_default_icon_namespace",
    "set_default_icon_pack",
    "INTEGRATION_PROTOCOL_VERSION",
    "GlassRuntimeIntegrationBridge",
    "IpcIntegrationAdapterScaffold",
    "InProcessIntegrationAdapter",
    "IntegrationClientContext",
    "IntegrationCommandEnvelope",
    "IntegrationEndpointSpec",
    "IntegrationEnvelopeMeta",
    "IntegrationError",
    "IntegrationEvent",
    "IntegrationQueryEnvelope",
    "IntegrationResponse",
    "IntegrationService",
    "IntegrationSnapshotRequest",
    "IntegrationValidationError",
    "LocalHttpIntegrationAdapter",
    "LocalHttpIntegrationConfig",
    "ReferenceWorkspaceState",
    "WebSocketIntegrationAdapterScaffold",
    "create_reference_workspace_service",
    "register_reference_workspace_endpoints",
    "CURRENT_WORKSPACE_SCHEMA_VERSION",
    "GlassWorkspaceState",
    "load_workspace_state",
    "save_workspace_state",
    "DashboardWidgetShell",
    "EmptyStateCard",
    "ErrorStateCard",
    "FormSectionShell",
    "LoadingStateCard",
    "PanelHeader",
    "QuickActionsStrip",
    "StatCard",
    "GlassRuntimeContext",
    "GlassVisibilityPolicy",
    "GlassVisibilityRule",
    "GlassWorkspaceRuntime",
    "build_glass_dialog_scene",
    "GlassLayoutController",
    "GlassPanelFrame",
    "GlassPanelSpec",
    "GlassPanelTemplate",
    "GlassTemplateActions",
    "GlassTemplateCards",
    "GlassTemplateSlots",
    "GlassWorkspaceTabSpec",
    "GlassWorkspaceTabs",
    "DEFAULT_THEME_ID",
    "GlassPalette",
    "GlassThemeManifest",
    "build_stylesheet",
    "get_palette",
    "get_theme_manifest",
    "list_theme_ids",
    "register_theme",
    "register_theme_overrides",
    "AssetCatalogEntrySpec",
    "DashboardCatalogEntrySpec",
    "GlassCatalogShell",
    "build_dashboard_catalog_entry",
    "iter_asset_catalog_specs",
    "iter_dashboard_catalog_specs",
]

def __getattr__(name: str):
    module_name = _SYMBOL_TO_MODULE.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = _import_module(module_name, __name__)
    value = getattr(module, name)
    _warn_legacy_root_import(name, module_name)
    globals()[name] = value
    return value

def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))

__legacy_api_restored__ = True
__migration_bridge_enabled__ = True
