import type { SupplierAccount, SupplierProductLink, SupplierPayable, SupplierPurchaseOrder, SupplierReceivingReceipt } from './types';

export const supplierAccounts: SupplierAccount[] = [
  {
    "id": "sup_beverages",
    "tradeName": "Bebidas del Centro",
    "legalName": "Bebidas del Centro SA de CV",
    "category": "bebidas",
    "status": "active",
    "notes": "Proveedor usado por Compra Inteligente para calendario, pagos y recepciones.",
    "contacts": [
      {
        "id": "sup_beverages_contact",
        "name": "Contacto Bebidas del Centro",
        "role": "Ventas",
        "phone": "5550102030",
        "whatsapp": "5550102030",
        "email": "ventas@proveedor.mx",
        "isPrimary": true
      }
    ],
    "visitRule": {
      "cadence": "weekly",
      "weekdays": [
        "viernes"
      ],
      "approximateTime": "10:30",
      "orderCutoffWeekday": "viernes",
      "orderCutoffTime": "17:00",
      "leadTimeDays": 2,
      "nextVisitDate": "2026-05-08",
      "nextOrderCutoff": "2026-05-04T17:00:00"
    },
    "terms": {
      "paymentCondition": "credit_15",
      "creditDays": 15,
      "minimumOrderCents": 550000,
      "creditLimitCents": 2750000,
      "usualDiscountBps": 5000,
      "shippingCostCents": 0,
      "returnPolicy": "Diferencias y daños requieren registro antes de cerrar recepción."
    },
    "createdAt": "2026-04-20T09:00:00",
    "updatedAt": "2026-05-02T09:00:00"
  },
  {
    "id": "sup_snacks",
    "tradeName": "Snacks MX",
    "legalName": "Snacks MX SA de CV",
    "category": "snacks",
    "status": "active",
    "notes": "Proveedor usado por Compra Inteligente para calendario, pagos y recepciones.",
    "contacts": [
      {
        "id": "sup_snacks_contact",
        "name": "Contacto Snacks MX",
        "role": "Ventas",
        "phone": "5550102030",
        "whatsapp": "5550102030",
        "email": "ventas@proveedor.mx",
        "isPrimary": true
      }
    ],
    "visitRule": {
      "cadence": "weekly",
      "weekdays": [
        "miercoles"
      ],
      "approximateTime": "10:30",
      "orderCutoffWeekday": "miercoles",
      "orderCutoffTime": "17:00",
      "leadTimeDays": 2,
      "nextVisitDate": "2026-05-06",
      "nextOrderCutoff": "2026-05-04T17:00:00"
    },
    "terms": {
      "paymentCondition": "credit_7",
      "creditDays": 7,
      "minimumOrderCents": 240000,
      "creditLimitCents": 1200000,
      "usualDiscountBps": 3000,
      "shippingCostCents": 0,
      "returnPolicy": "Diferencias y daños requieren registro antes de cerrar recepción."
    },
    "createdAt": "2026-04-20T09:00:00",
    "updatedAt": "2026-05-02T09:00:00"
  },
  {
    "id": "sup_bakery",
    "tradeName": "Panadería La Ruta",
    "legalName": "Panadería La Ruta SA de CV",
    "category": "panaderia",
    "status": "active",
    "notes": "Proveedor usado por Compra Inteligente para calendario, pagos y recepciones.",
    "contacts": [
      {
        "id": "sup_bakery_contact",
        "name": "Contacto Panadería La Ruta",
        "role": "Ventas",
        "phone": "5550102030",
        "whatsapp": "5550102030",
        "email": "ventas@proveedor.mx",
        "isPrimary": true
      }
    ],
    "visitRule": {
      "cadence": "weekly",
      "weekdays": [
        "martes"
      ],
      "approximateTime": "10:30",
      "orderCutoffWeekday": "martes",
      "orderCutoffTime": "17:00",
      "leadTimeDays": 2,
      "nextVisitDate": "2026-05-05",
      "nextOrderCutoff": "2026-05-04T17:00:00"
    },
    "terms": {
      "paymentCondition": "credit_7",
      "creditDays": 7,
      "minimumOrderCents": 180000,
      "creditLimitCents": 900000,
      "usualDiscountBps": 0,
      "shippingCostCents": 0,
      "returnPolicy": "Diferencias y daños requieren registro antes de cerrar recepción."
    },
    "createdAt": "2026-04-20T09:00:00",
    "updatedAt": "2026-05-02T09:00:00"
  },
  {
    "id": "sup_dairy",
    "tradeName": "Lácteos del Norte",
    "legalName": "Lácteos del Norte SA de CV",
    "category": "lacteos",
    "status": "paused",
    "notes": "Proveedor usado por Compra Inteligente para calendario, pagos y recepciones.",
    "contacts": [
      {
        "id": "sup_dairy_contact",
        "name": "Contacto Lácteos del Norte",
        "role": "Ventas",
        "phone": "5550102030",
        "whatsapp": "5550102030",
        "email": "ventas@proveedor.mx",
        "isPrimary": true
      }
    ],
    "visitRule": {
      "cadence": "weekly",
      "weekdays": [
        "jueves"
      ],
      "approximateTime": "10:30",
      "orderCutoffWeekday": "jueves",
      "orderCutoffTime": "17:00",
      "leadTimeDays": 2,
      "nextVisitDate": "2026-05-07",
      "nextOrderCutoff": "2026-05-04T17:00:00"
    },
    "terms": {
      "paymentCondition": "credit_7",
      "creditDays": 7,
      "minimumOrderCents": 120000,
      "creditLimitCents": 600000,
      "usualDiscountBps": 2500,
      "shippingCostCents": 0,
      "returnPolicy": "Diferencias y daños requieren registro antes de cerrar recepción."
    },
    "createdAt": "2026-04-20T09:00:00",
    "updatedAt": "2026-05-02T09:00:00"
  },
  {
    "id": "sup_clean",
    "tradeName": "Limpieza Uno",
    "legalName": "Limpieza Uno SA de CV",
    "category": "limpieza",
    "status": "active",
    "notes": "Proveedor usado por Compra Inteligente para calendario, pagos y recepciones.",
    "contacts": [
      {
        "id": "sup_clean_contact",
        "name": "Contacto Limpieza Uno",
        "role": "Ventas",
        "phone": "5550102030",
        "whatsapp": "5550102030",
        "email": "ventas@proveedor.mx",
        "isPrimary": true
      }
    ],
    "visitRule": {
      "cadence": "weekly",
      "weekdays": [
        "lunes"
      ],
      "approximateTime": "10:30",
      "orderCutoffWeekday": "lunes",
      "orderCutoffTime": "17:00",
      "leadTimeDays": 2,
      "nextVisitDate": "2026-05-04",
      "nextOrderCutoff": "2026-05-04T17:00:00"
    },
    "terms": {
      "paymentCondition": "credit_30",
      "creditDays": 30,
      "minimumOrderCents": 90000,
      "creditLimitCents": 450000,
      "usualDiscountBps": 1500,
      "shippingCostCents": 0,
      "returnPolicy": "Diferencias y daños requieren registro antes de cerrar recepción."
    },
    "createdAt": "2026-04-20T09:00:00",
    "updatedAt": "2026-05-02T09:00:00"
  },
  {
    "id": "sup_pharma",
    "tradeName": "Farmacia Barrial",
    "legalName": "Farmacia Barrial SA de CV",
    "category": "farmacia",
    "status": "blocked",
    "notes": "Proveedor usado por Compra Inteligente para calendario, pagos y recepciones.",
    "contacts": [
      {
        "id": "sup_pharma_contact",
        "name": "Contacto Farmacia Barrial",
        "role": "Ventas",
        "phone": "5550102030",
        "whatsapp": "5550102030",
        "email": "ventas@proveedor.mx",
        "isPrimary": true
      }
    ],
    "visitRule": {
      "cadence": "weekly",
      "weekdays": [
        "viernes"
      ],
      "approximateTime": "10:30",
      "orderCutoffWeekday": "viernes",
      "orderCutoffTime": "17:00",
      "leadTimeDays": 2,
      "nextVisitDate": "2026-05-08",
      "nextOrderCutoff": "2026-05-04T17:00:00"
    },
    "terms": {
      "paymentCondition": "credit_15",
      "creditDays": 15,
      "minimumOrderCents": 130000,
      "creditLimitCents": 650000,
      "usualDiscountBps": 3500,
      "shippingCostCents": 0,
      "returnPolicy": "Diferencias y daños requieren registro antes de cerrar recepción."
    },
    "createdAt": "2026-04-20T09:00:00",
    "updatedAt": "2026-05-02T09:00:00"
  }
] as const satisfies SupplierAccount[];

export const supplierProductLinks: SupplierProductLink[] = [
  {
    "id": "prod_001",
    "productId": "prod_001",
    "sku": "BEB-COCA600",
    "name": "Coca-Cola 600 ml",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 12,
    "recentCostCents": 2800,
    "currentStockUnits": 18,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 11,
    "grossMarginBps": -2727,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_002",
    "productId": "prod_002",
    "sku": "BEB-AGUA1L",
    "name": "Agua natural 1L",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 12,
    "recentCostCents": 1100,
    "currentStockUnits": 62,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 2142,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_003",
    "productId": "prod_003",
    "sku": "BEB-ELEC-MORA",
    "name": "Electrolit mora azul",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 12,
    "recentCostCents": 2100,
    "currentStockUnits": 9,
    "lowStockThresholdUnits": 4,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 3225,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_004",
    "productId": "prod_004",
    "sku": "SNK-SAB-SAL",
    "name": "Sabritas sal 45g",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 950,
    "currentStockUnits": 14,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 4411,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_005",
    "productId": "prod_005",
    "sku": "SNK-DOR-NACHO",
    "name": "Doritos nacho",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1020,
    "currentStockUnits": 11,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4333,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_006",
    "productId": "prod_006",
    "sku": "SNK-GAL-SURT",
    "name": "Galleta surtida",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 700,
    "currentStockUnits": 92,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 5333,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_007",
    "productId": "prod_007",
    "sku": "PAN-BOL-01",
    "name": "Bolillo pieza",
    "category": "panaderia",
    "supplierId": "sup_bakery",
    "packageSize": 10,
    "minPurchaseUnits": 12,
    "recentCostCents": 120,
    "currentStockUnits": 38,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 20,
    "grossMarginBps": 6000,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Panadería La Ruta",
    "isPrimary": true
  },
  {
    "id": "prod_008",
    "productId": "prod_008",
    "sku": "PAN-CONCHA",
    "name": "Pan dulce concha",
    "category": "panaderia",
    "supplierId": "sup_bakery",
    "packageSize": 10,
    "minPurchaseUnits": 12,
    "recentCostCents": 430,
    "currentStockUnits": 8,
    "lowStockThresholdUnits": 4,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5699,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Panadería La Ruta",
    "isPrimary": true
  },
  {
    "id": "prod_009",
    "productId": "prod_009",
    "sku": "LAC-LECHE1",
    "name": "Leche entera 1L",
    "category": "lacteos",
    "supplierId": "sup_dairy",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1650,
    "currentStockUnits": 19,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 3125,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Lácteos del Norte",
    "isPrimary": true
  },
  {
    "id": "prod_010",
    "productId": "prod_010",
    "sku": "LAC-YOG-BEB",
    "name": "Yogurt bebible",
    "category": "lacteos",
    "supplierId": "sup_dairy",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 780,
    "currentStockUnits": 46,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 4000,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Lácteos del Norte",
    "isPrimary": true
  },
  {
    "id": "prod_011",
    "productId": "prod_011",
    "sku": "LIM-CLORO1",
    "name": "Cloro 1L",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 10,
    "minPurchaseUnits": 12,
    "recentCostCents": 900,
    "currentStockUnits": 18,
    "lowStockThresholdUnits": 4,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 5000,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_012",
    "productId": "prod_012",
    "sku": "LIM-PAPEL4",
    "name": "Papel higiénico 4p",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 10,
    "minPurchaseUnits": 12,
    "recentCostCents": 2450,
    "currentStockUnits": 9,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3000,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_013",
    "productId": "prod_013",
    "sku": "FAR-PARA",
    "name": "Paracetamol caja",
    "category": "farmacia",
    "supplierId": "sup_pharma",
    "packageSize": 10,
    "minPurchaseUnits": 12,
    "recentCostCents": 2200,
    "currentStockUnits": 4,
    "lowStockThresholdUnits": 3,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 5111,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Farmacia Barrial",
    "isPrimary": true
  },
  {
    "id": "prod_014",
    "productId": "prod_014",
    "sku": "FAR-SUERO",
    "name": "Suero oral polvo",
    "category": "farmacia",
    "supplierId": "sup_pharma",
    "packageSize": 10,
    "minPurchaseUnits": 12,
    "recentCostCents": 850,
    "currentStockUnits": 3,
    "lowStockThresholdUnits": 3,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 4687,
    "lastCostUpdateAt": "2026-05-01T09:00:00",
    "supplierName": "Farmacia Barrial",
    "isPrimary": true
  },
  {
    "id": "prod_015",
    "productId": "prod_015",
    "sku": "LIM-SKU-015",
    "name": "Producto operativo 015 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 2675,
    "currentStockUnits": 20,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_016",
    "productId": "prod_016",
    "sku": "BEB-SKU-016",
    "name": "Producto operativo 016 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 2820,
    "currentStockUnits": 27,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_017",
    "productId": "prod_017",
    "sku": "SNA-SKU-017",
    "name": "Producto operativo 017 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 500,
    "currentStockUnits": 34,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5440,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_018",
    "productId": "prod_018",
    "sku": "ABA-SKU-018",
    "name": "Producto operativo 018 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 645,
    "currentStockUnits": 41,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 2800,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_019",
    "productId": "prod_019",
    "sku": "LIM-SKU-019",
    "name": "Producto operativo 019 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 790,
    "currentStockUnits": 48,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3130,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_020",
    "productId": "prod_020",
    "sku": "BEB-SKU-020",
    "name": "Producto operativo 020 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 935,
    "currentStockUnits": 55,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 3460,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_021",
    "productId": "prod_021",
    "sku": "SNA-SKU-021",
    "name": "Producto operativo 021 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1080,
    "currentStockUnits": 62,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 4,
    "grossMarginBps": 3790,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_022",
    "productId": "prod_022",
    "sku": "ABA-SKU-022",
    "name": "Producto operativo 022 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 1225,
    "currentStockUnits": 69,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 4120,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_023",
    "productId": "prod_023",
    "sku": "LIM-SKU-023",
    "name": "Producto operativo 023 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 1370,
    "currentStockUnits": 76,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4450,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_024",
    "productId": "prod_024",
    "sku": "BEB-SKU-024",
    "name": "Producto operativo 024 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 1515,
    "currentStockUnits": 83,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_025",
    "productId": "prod_025",
    "sku": "SNA-SKU-025",
    "name": "Producto operativo 025 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1660,
    "currentStockUnits": 5,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_026",
    "productId": "prod_026",
    "sku": "ABA-SKU-026",
    "name": "Producto operativo 026 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 1805,
    "currentStockUnits": 12,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5440,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_027",
    "productId": "prod_027",
    "sku": "LIM-SKU-027",
    "name": "Producto operativo 027 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 1950,
    "currentStockUnits": 19,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 2800,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_028",
    "productId": "prod_028",
    "sku": "BEB-SKU-028",
    "name": "Producto operativo 028 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 2095,
    "currentStockUnits": 26,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3130,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_029",
    "productId": "prod_029",
    "sku": "SNA-SKU-029",
    "name": "Producto operativo 029 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 2240,
    "currentStockUnits": 33,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 3460,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_030",
    "productId": "prod_030",
    "sku": "ABA-SKU-030",
    "name": "Producto operativo 030 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 2385,
    "currentStockUnits": 40,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 4,
    "grossMarginBps": 3790,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_031",
    "productId": "prod_031",
    "sku": "LIM-SKU-031",
    "name": "Producto operativo 031 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 2530,
    "currentStockUnits": 47,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 4120,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_032",
    "productId": "prod_032",
    "sku": "BEB-SKU-032",
    "name": "Producto operativo 032 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 2675,
    "currentStockUnits": 54,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4450,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_033",
    "productId": "prod_033",
    "sku": "SNA-SKU-033",
    "name": "Producto operativo 033 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 2820,
    "currentStockUnits": 61,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_034",
    "productId": "prod_034",
    "sku": "ABA-SKU-034",
    "name": "Producto operativo 034 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 500,
    "currentStockUnits": 68,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_035",
    "productId": "prod_035",
    "sku": "LIM-SKU-035",
    "name": "Producto operativo 035 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 645,
    "currentStockUnits": 75,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5440,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_036",
    "productId": "prod_036",
    "sku": "BEB-SKU-036",
    "name": "Producto operativo 036 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 790,
    "currentStockUnits": 82,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 2800,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_037",
    "productId": "prod_037",
    "sku": "SNA-SKU-037",
    "name": "Producto operativo 037 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 935,
    "currentStockUnits": 4,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3130,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_038",
    "productId": "prod_038",
    "sku": "ABA-SKU-038",
    "name": "Producto operativo 038 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 1080,
    "currentStockUnits": 11,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 3460,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_039",
    "productId": "prod_039",
    "sku": "LIM-SKU-039",
    "name": "Producto operativo 039 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 1225,
    "currentStockUnits": 18,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 4,
    "grossMarginBps": 3790,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_040",
    "productId": "prod_040",
    "sku": "BEB-SKU-040",
    "name": "Producto operativo 040 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 1370,
    "currentStockUnits": 25,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 4120,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_041",
    "productId": "prod_041",
    "sku": "SNA-SKU-041",
    "name": "Producto operativo 041 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1515,
    "currentStockUnits": 32,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4450,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_042",
    "productId": "prod_042",
    "sku": "ABA-SKU-042",
    "name": "Producto operativo 042 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 1660,
    "currentStockUnits": 39,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_043",
    "productId": "prod_043",
    "sku": "LIM-SKU-043",
    "name": "Producto operativo 043 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 1805,
    "currentStockUnits": 46,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_044",
    "productId": "prod_044",
    "sku": "BEB-SKU-044",
    "name": "Producto operativo 044 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 1950,
    "currentStockUnits": 53,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5440,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_045",
    "productId": "prod_045",
    "sku": "SNA-SKU-045",
    "name": "Producto operativo 045 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 2095,
    "currentStockUnits": 60,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 2800,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_046",
    "productId": "prod_046",
    "sku": "ABA-SKU-046",
    "name": "Producto operativo 046 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 2240,
    "currentStockUnits": 67,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3130,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_047",
    "productId": "prod_047",
    "sku": "LIM-SKU-047",
    "name": "Producto operativo 047 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 2385,
    "currentStockUnits": 74,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 3460,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_048",
    "productId": "prod_048",
    "sku": "BEB-SKU-048",
    "name": "Producto operativo 048 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 2530,
    "currentStockUnits": 81,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 4,
    "grossMarginBps": 3790,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_049",
    "productId": "prod_049",
    "sku": "SNA-SKU-049",
    "name": "Producto operativo 049 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 2675,
    "currentStockUnits": 3,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 4120,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_050",
    "productId": "prod_050",
    "sku": "ABA-SKU-050",
    "name": "Producto operativo 050 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 2820,
    "currentStockUnits": 10,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4450,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_051",
    "productId": "prod_051",
    "sku": "LIM-SKU-051",
    "name": "Producto operativo 051 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 500,
    "currentStockUnits": 17,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_052",
    "productId": "prod_052",
    "sku": "BEB-SKU-052",
    "name": "Producto operativo 052 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 645,
    "currentStockUnits": 24,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_053",
    "productId": "prod_053",
    "sku": "SNA-SKU-053",
    "name": "Producto operativo 053 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 790,
    "currentStockUnits": 31,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5440,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_054",
    "productId": "prod_054",
    "sku": "ABA-SKU-054",
    "name": "Producto operativo 054 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 935,
    "currentStockUnits": 38,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 2800,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_055",
    "productId": "prod_055",
    "sku": "LIM-SKU-055",
    "name": "Producto operativo 055 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 1080,
    "currentStockUnits": 45,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3130,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_056",
    "productId": "prod_056",
    "sku": "BEB-SKU-056",
    "name": "Producto operativo 056 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 1225,
    "currentStockUnits": 52,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 3460,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_057",
    "productId": "prod_057",
    "sku": "SNA-SKU-057",
    "name": "Producto operativo 057 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1370,
    "currentStockUnits": 59,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 4,
    "grossMarginBps": 3790,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_058",
    "productId": "prod_058",
    "sku": "ABA-SKU-058",
    "name": "Producto operativo 058 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 1515,
    "currentStockUnits": 66,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 4120,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_059",
    "productId": "prod_059",
    "sku": "LIM-SKU-059",
    "name": "Producto operativo 059 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 1660,
    "currentStockUnits": 73,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4450,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_060",
    "productId": "prod_060",
    "sku": "BEB-SKU-060",
    "name": "Producto operativo 060 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 1805,
    "currentStockUnits": 80,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_061",
    "productId": "prod_061",
    "sku": "SNA-SKU-061",
    "name": "Producto operativo 061 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1950,
    "currentStockUnits": 2,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_062",
    "productId": "prod_062",
    "sku": "ABA-SKU-062",
    "name": "Producto operativo 062 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 2095,
    "currentStockUnits": 9,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5440,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_063",
    "productId": "prod_063",
    "sku": "LIM-SKU-063",
    "name": "Producto operativo 063 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 2240,
    "currentStockUnits": 16,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 2800,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_064",
    "productId": "prod_064",
    "sku": "BEB-SKU-064",
    "name": "Producto operativo 064 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 2385,
    "currentStockUnits": 23,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3130,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_065",
    "productId": "prod_065",
    "sku": "SNA-SKU-065",
    "name": "Producto operativo 065 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 2530,
    "currentStockUnits": 30,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 3460,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_066",
    "productId": "prod_066",
    "sku": "ABA-SKU-066",
    "name": "Producto operativo 066 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 2675,
    "currentStockUnits": 37,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 4,
    "grossMarginBps": 3790,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_067",
    "productId": "prod_067",
    "sku": "LIM-SKU-067",
    "name": "Producto operativo 067 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 2820,
    "currentStockUnits": 44,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 4120,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_068",
    "productId": "prod_068",
    "sku": "BEB-SKU-068",
    "name": "Producto operativo 068 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 500,
    "currentStockUnits": 51,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4450,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_069",
    "productId": "prod_069",
    "sku": "SNA-SKU-069",
    "name": "Producto operativo 069 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 645,
    "currentStockUnits": 58,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_070",
    "productId": "prod_070",
    "sku": "ABA-SKU-070",
    "name": "Producto operativo 070 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 790,
    "currentStockUnits": 65,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_071",
    "productId": "prod_071",
    "sku": "LIM-SKU-071",
    "name": "Producto operativo 071 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 935,
    "currentStockUnits": 72,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 9,
    "grossMarginBps": 5440,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_072",
    "productId": "prod_072",
    "sku": "BEB-SKU-072",
    "name": "Producto operativo 072 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 1080,
    "currentStockUnits": 79,
    "lowStockThresholdUnits": 5,
    "averageDailySalesUnits": 1,
    "grossMarginBps": 2800,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_073",
    "productId": "prod_073",
    "sku": "SNA-SKU-073",
    "name": "Producto operativo 073 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1225,
    "currentStockUnits": 1,
    "lowStockThresholdUnits": 6,
    "averageDailySalesUnits": 2,
    "grossMarginBps": 3130,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_074",
    "productId": "prod_074",
    "sku": "ABA-SKU-074",
    "name": "Producto operativo 074 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 1370,
    "currentStockUnits": 8,
    "lowStockThresholdUnits": 7,
    "averageDailySalesUnits": 3,
    "grossMarginBps": 3460,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_075",
    "productId": "prod_075",
    "sku": "LIM-SKU-075",
    "name": "Producto operativo 075 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 1515,
    "currentStockUnits": 15,
    "lowStockThresholdUnits": 8,
    "averageDailySalesUnits": 4,
    "grossMarginBps": 3790,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  },
  {
    "id": "prod_076",
    "productId": "prod_076",
    "sku": "BEB-SKU-076",
    "name": "Producto operativo 076 bebidas",
    "category": "bebidas",
    "supplierId": "sup_beverages",
    "packageSize": 24,
    "minPurchaseUnits": 24,
    "recentCostCents": 1660,
    "currentStockUnits": 22,
    "lowStockThresholdUnits": 9,
    "averageDailySalesUnits": 5,
    "grossMarginBps": 4120,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Bebidas del Centro",
    "isPrimary": true
  },
  {
    "id": "prod_077",
    "productId": "prod_077",
    "sku": "SNA-SKU-077",
    "name": "Producto operativo 077 snacks",
    "category": "snacks",
    "supplierId": "sup_snacks",
    "packageSize": 12,
    "minPurchaseUnits": 12,
    "recentCostCents": 1805,
    "currentStockUnits": 29,
    "lowStockThresholdUnits": 10,
    "averageDailySalesUnits": 6,
    "grossMarginBps": 4450,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_078",
    "productId": "prod_078",
    "sku": "ABA-SKU-078",
    "name": "Producto operativo 078 abarrotes",
    "category": "abarrotes",
    "supplierId": "sup_snacks",
    "packageSize": 10,
    "minPurchaseUnits": 10,
    "recentCostCents": 1950,
    "currentStockUnits": 36,
    "lowStockThresholdUnits": 11,
    "averageDailySalesUnits": 7,
    "grossMarginBps": 4780,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Snacks MX",
    "isPrimary": true
  },
  {
    "id": "prod_079",
    "productId": "prod_079",
    "sku": "LIM-SKU-079",
    "name": "Producto operativo 079 limpieza",
    "category": "limpieza",
    "supplierId": "sup_clean",
    "packageSize": 8,
    "minPurchaseUnits": 8,
    "recentCostCents": 2095,
    "currentStockUnits": 43,
    "lowStockThresholdUnits": 12,
    "averageDailySalesUnits": 8,
    "grossMarginBps": 5110,
    "lastCostUpdateAt": "2026-04-28T11:00:00",
    "supplierName": "Limpieza Uno",
    "isPrimary": true
  }
] as const satisfies SupplierProductLink[];


export const supplierPayables: SupplierPayable[] = [
  { id: "pay_001", supplierId: "sup_beverages", supplierName: "Bebidas del Centro", orderId: "po_001", dueDate: "2026-05-06T18:00:00", amountCents: 320000, status: "due_soon", notes: "Pago próximo; Compra Inteligente debe cuidar caja." },
  { id: "pay_002", supplierId: "sup_snacks", supplierName: "Snacks MX", orderId: "po_002", dueDate: "2026-05-09T18:00:00", amountCents: 176000, status: "scheduled" },
  { id: "pay_003", supplierId: "sup_dairy", supplierName: "Lácteos del Norte", orderId: "po_003", dueDate: "2026-05-01T18:00:00", amountCents: 98000, status: "overdue", notes: "Proveedor pausado por pago vencido." }
];

export const supplierOrders: SupplierPurchaseOrder[] = [
  { id: "po_001", folio: "PO-2601", supplierId: "sup_beverages", supplierName: "Bebidas del Centro", source: "smart_purchase", status: "sent", createdAt: "2026-05-01T13:00:00", expectedReceptionDate: "2026-05-03T11:00:00", expectedPaymentDate: "2026-05-06T18:00:00", totalCents: 320000, auditTrail: ["recomendacion_generada", "pedido_creado", "pedido_enviado"], lines: [] },
  { id: "po_002", folio: "PO-2602", supplierId: "sup_snacks", supplierName: "Snacks MX", source: "manual", status: "partially_received", createdAt: "2026-04-30T12:00:00", expectedReceptionDate: "2026-05-02T12:00:00", expectedPaymentDate: "2026-05-09T18:00:00", totalCents: 176000, auditTrail: ["pedido_manual", "recepcion_parcial"], lines: [] }
];

export const receivingQueue: SupplierReceivingReceipt[] = [
  { id: "rec_001", orderId: "po_002", supplierId: "sup_snacks", supplierName: "Snacks MX", status: "with_differences", expectedAt: "2026-05-02T12:00:00", receivedAt: "2026-05-02T14:00:00", differences: [{ productId: "prod_004", sku: "SNK-SAB-SAL", name: "Sabritas sal 45g", expectedUnits: 48, receivedUnits: 36, reason: "partial", note: "Faltaron 12 piezas. Registrar antes de cerrar pedido." }] },
  { id: "rec_002", orderId: "po_001", supplierId: "sup_beverages", supplierName: "Bebidas del Centro", status: "pending", expectedAt: "2026-05-03T11:00:00", differences: [] }
];


export const supplierLifecycleFixtures = {
  businessId: "biz_prisma_demo_conveniencia",
  branchId: "branch_matriz",
  actor: {
    id: "usr_admin_prisma",
    name: "Administrador PRISMA",
    role: "Administrador"
  },
  cashPolicy: {
    availableCashCents: 920000,
    reserveCashCents: 180000,
    maxAutoApprovalCents: 250000,
    requiresOwnerApprovalAboveCents: 420000
  },
  unresolvedSyncSignals: [
    {
      id: "sync_pending_tablet_ventas_001",
      source: "Tablet POS",
      message: "Hay ventas pendientes de sincronizar. La recomendacion puede cambiar cuando se actualicen los datos.",
      severity: "medium"
    },
    {
      id: "sync_low_stock_tablet_002",
      source: "Tablet POS",
      message: "La Tablet reporto producto critico en mostrador. Revisa Compra Inteligente antes de aprobar pedido.",
      severity: "high"
    }
  ],
  policyNotes: [
    "PRISMA recomienda; el usuario aprueba.",
    "Proveedor bloqueado no recibe pedido nuevo.",
    "Recepcion confirmada crea movimiento de inventario y auditoria.",
    "Cuenta por pagar conserva origen de pedido o recepcion.",
    "Tablet solo recibe senales ligeras; no administra proveedores."
  ]
} as const;
