import type { PrismaMobileBranch, PrismaMobileInventoryItem } from "./prisma-app-api-contracts";
import type { PrismaMobileClientSnapshot, PrismaMobileSnapshotPayload } from "./prisma-mobile-snapshot-contract";
import { buildPrismaMobileActionInbox } from "./prisma-mobile-action-inbox";
import { buildPrismaMobileCommandCenter, type PrismaMobileCommandTone } from "./prisma-mobile-command-center";
import { buildPrismaMobileDecisionLedger } from "./prisma-mobile-decision-ledger";
import { buildPrismaMobilePulseTimeline } from "./prisma-mobile-pulse-timeline";
import { formatSignedMxnFromCents } from "./prisma-mobile-formatters";

export const PRISMA_MOBILE_HEALTH_RADAR_CONTRACT_ID = "PRISMA_APP_MOBILE_25_HEALTH_RADAR";
export type PrismaMobileHealthRadarAxisId = "caja" | "ventas" | "inventario" | "alertas" | "sucursales" | "datos";
export type PrismaMobileHealthRadarTrend = "subiendo" | "estable" | "bajando";
export type PrismaMobileHealthRadarAxis = { id: PrismaMobileHealthRadarAxisId; label: string; score: number; tone: PrismaMobileCommandTone; trend: PrismaMobileHealthRadarTrend; headline: string; detail: string; evidence: string[]; nextCheck: string; };
export type PrismaMobileHealthRadarWatch = { id: string; label: string; value: string; detail: string; tone: PrismaMobileCommandTone; };
export type PrismaMobileHealthRadar = { contractId: typeof PRISMA_MOBILE_HEALTH_RADAR_CONTRACT_ID; healthScore: number; healthLabel: string; tone: PrismaMobileCommandTone; weakestArea: string; strongestArea: string; ownerSummary: string; axes: PrismaMobileHealthRadarAxis[]; watchlist: PrismaMobileHealthRadarWatch[]; guardrails: string[]; nextReview: string; };
function clamp(value: number, min = 0, max = 100): number { return Math.min(max, Math.max(min, Math.round(value))); }
function toneForScore(score: number, offline = false): PrismaMobileCommandTone { if (offline) return "offline"; if (score < 45) return "urgente"; if (score < 75) return "revisar"; return "sano"; }
function trendFromDelta(delta: string): PrismaMobileHealthRadarTrend { const v = delta.trim(); if (v.startsWith("-")) return "bajando"; if (v.startsWith("+") || v.includes("arriba")) return "subiendo"; return "estable"; }
function average(values: number[]): number { return values.length === 0 ? 100 : clamp(values.reduce((a, v) => a + v, 0) / values.length); }
function criticalInventoryItems(snapshot: PrismaMobileSnapshotPayload): PrismaMobileInventoryItem[] { return snapshot.inventoryWatchlist.items.filter((item) => item.state === "critico" || item.state === "reponer"); }
function problematicBranches(snapshot: PrismaMobileSnapshotPayload): PrismaMobileBranch[] { return snapshot.branches.branches.filter((branch) => branch.status !== "sano"); }
function buildAxes(client: PrismaMobileClientSnapshot): PrismaMobileHealthRadarAxis[] {
 const snapshot = client.snapshot;
 const cashExposure = Math.abs(snapshot.cashCurrent.differenceCents);
 const cashScore = clamp(100 - (cashExposure >= 20000 ? 42 : cashExposure >= 5000 ? 24 : cashExposure > 0 ? 10 : 0));
 const salesScore = clamp(100 - (snapshot.salesToday.tickets === 0 ? 38 : snapshot.salesToday.averageTicketCents === 0 ? 30 : trendFromDelta(snapshot.salesToday.deltaAgainstYesterday) === "bajando" ? 16 : 0));
 const inventoryScore = clamp(100 - (snapshot.inventoryWatchlist.counts.critical * 18 + snapshot.inventoryWatchlist.counts.reorder * 8 + snapshot.inventoryWatchlist.counts.overstock * 3));
 const alertScore = clamp(100 - (snapshot.alerts.counts.critical * 20 + snapshot.alerts.counts.high * 10 + snapshot.alerts.counts.medium * 5));
 const branchScore = clamp(100 - (snapshot.branches.counts.offline * 28 + snapshot.branches.counts.urgent * 18 + snapshot.branches.counts.review * 8));
 const upstreamTotal = snapshot.health.upstreams.length || 1;
 const upstreamOk = snapshot.health.upstreams.filter((upstream) => upstream.ok).length;
 const dataScore = clamp((upstreamOk / upstreamTotal) * 100 - (client.stale ? 18 : 0) - client.errors.length * 12);
 return [
  { id: "caja", label: "Caja", score: cashScore, tone: toneForScore(cashScore), trend: cashExposure > 0 ? "bajando" : "estable", headline: cashExposure > 0 ? "Caja con diferencia visible" : "Caja sin diferencia crítica", detail: `${snapshot.cashCurrent.status} · diferencia ${formatSignedMxnFromCents(snapshot.cashCurrent.differenceCents)}`, evidence: [`Esperado: ${snapshot.cashCurrent.expectedLabel}`, `Contado: ${snapshot.cashCurrent.countedLabel}`, `Último corte: ${snapshot.cashCurrent.lastCut}`], nextCheck: cashExposure > 0 ? "Confirmar corte antes de mover efectivo." : "Revisar en cierre normal." },
  { id: "ventas", label: "Ventas", score: salesScore, tone: toneForScore(salesScore), trend: trendFromDelta(snapshot.salesToday.deltaAgainstYesterday), headline: snapshot.salesToday.tickets > 0 ? "Venta con actividad registrada" : "Sin tickets registrados", detail: `${snapshot.salesToday.totalSalesLabel} · ${snapshot.salesToday.tickets} tickets · ticket promedio ${snapshot.salesToday.averageTicketLabel}`, evidence: [`Variación: ${snapshot.salesToday.deltaAgainstYesterday}`, `Categoría fuerte: ${snapshot.salesToday.strongCategory}`, `Puntos de venta: ${snapshot.salesToday.timeline.length}`], nextCheck: snapshot.salesToday.tickets === 0 ? "Confirmar que Tablet esté registrando venta." : "Comparar contra hora pico y cierre." },
  { id: "inventario", label: "Inventario", score: inventoryScore, tone: toneForScore(inventoryScore), trend: snapshot.inventoryWatchlist.counts.critical > 0 ? "bajando" : "estable", headline: snapshot.inventoryWatchlist.counts.critical > 0 ? "Productos críticos en piso" : "Inventario bajo control operativo", detail: `${snapshot.inventoryWatchlist.counts.critical} críticos · ${snapshot.inventoryWatchlist.counts.reorder} para reponer · ${snapshot.inventoryWatchlist.counts.overstock} sobrestock`, evidence: criticalInventoryItems(snapshot).slice(0, 3).map((item) => `${item.sku}: ${item.stock}`), nextCheck: snapshot.inventoryWatchlist.counts.critical > 0 ? "Validar existencia física antes del siguiente pico." : "Revisar sugerencias de reabasto." },
  { id: "alertas", label: "Alertas", score: alertScore, tone: toneForScore(alertScore), trend: snapshot.alerts.counts.critical > 0 || snapshot.alerts.counts.high > 0 ? "bajando" : "estable", headline: snapshot.alerts.counts.total > 0 ? "Alertas activas que requieren mirada" : "Sin alertas activas", detail: `${snapshot.alerts.counts.total} alertas · ${snapshot.alerts.counts.critical} críticas · ${snapshot.alerts.counts.high} altas`, evidence: snapshot.alerts.alerts.slice(0, 3).map((alert) => `${alert.area}: ${alert.title}`), nextCheck: snapshot.alerts.counts.total > 0 ? "Atender primero críticas y altas." : "Mantener monitoreo normal." },
  { id: "sucursales", label: "Sucursales", score: branchScore, tone: toneForScore(branchScore, snapshot.branches.counts.offline > 0), trend: snapshot.branches.counts.offline > 0 || snapshot.branches.counts.urgent > 0 ? "bajando" : "estable", headline: snapshot.branches.counts.offline > 0 ? "Sucursales sin señal" : snapshot.branches.counts.review > 0 ? "Sucursales para revisar" : "Sucursales sanas", detail: `${snapshot.branches.counts.healthy}/${snapshot.branches.counts.total} sanas · ${snapshot.branches.counts.offline} offline`, evidence: problematicBranches(snapshot).slice(0, 3).map((branch) => `${branch.name}: ${branch.cashState} · ${branch.syncLag}`), nextCheck: snapshot.branches.counts.offline > 0 ? "Contactar responsable antes de decisiones sensibles." : "Revisar al cierre." },
  { id: "datos", label: "Datos", score: dataScore, tone: toneForScore(dataScore, client.source === "local-cache" || client.source === "unavailable"), trend: client.stale ? "bajando" : "estable", headline: client.stale ? "Lectura con respaldo local" : "Datos conectados disponibles", detail: `${upstreamOk}/${upstreamTotal} fuentes OK · fuente móvil ${client.source}`, evidence: client.errors.length > 0 ? client.errors.slice(0, 3) : snapshot.health.upstreams.slice(0, 3).map((upstream) => `${upstream.id}: ${upstream.ok ? "OK" : "revisar"}`), nextCheck: client.stale ? "Actualizar antes de mandar reporte final." : "Apto para supervisión móvil." }
 ];
}
function buildWatchlist(client: PrismaMobileClientSnapshot, axes: PrismaMobileHealthRadarAxis[]): PrismaMobileHealthRadarWatch[] {
 const snapshot = client.snapshot; const command = buildPrismaMobileCommandCenter(client); const inbox = buildPrismaMobileActionInbox(client); const ledger = buildPrismaMobileDecisionLedger(client); const timeline = buildPrismaMobilePulseTimeline(client); const weakest = [...axes].sort((a, b) => a.score - b.score)[0]; const topAction = inbox.lanes.flatMap((lane) => lane.actions).sort((a, b) => b.priorityScore - a.priorityScore)[0]; const lastLedger = ledger.entries[0]; const nextEvent = timeline.events.find((event) => event.tone !== "sano") ?? timeline.events[0];
 return [
  { id: "weakest-axis", label: "Zona más delicada", value: `${weakest.label} ${weakest.score}/100`, detail: weakest.headline, tone: weakest.tone },
  { id: "owner-action", label: "Acción del dueño", value: topAction ? topAction.title : "Sin acción urgente", detail: topAction ? topAction.recommendedAction : "Mantener vigilancia de cierre.", tone: topAction ? topAction.tone : "sano" },
  { id: "decision-evidence", label: "Evidencia reciente", value: lastLedger ? lastLedger.title : "Bitácora limpia", detail: lastLedger ? lastLedger.evidence.slice(0, 2).join(" · ") : "Sin eventos delicados para registrar.", tone: lastLedger ? lastLedger.tone : "sano" },
  { id: "timeline-check", label: "Siguiente revisión", value: nextEvent ? nextEvent.title : "Cierre normal", detail: nextEvent ? nextEvent.nextCheck : `Readiness ${command.readinessScore}/100`, tone: nextEvent ? nextEvent.tone : command.riskTone },
  { id: "business-rhythm", label: "Ritmo comercial", value: snapshot.salesToday.totalSalesLabel, detail: `${snapshot.salesToday.tickets} tickets · ${snapshot.salesToday.strongCategory}`, tone: snapshot.salesToday.tickets > 0 ? "sano" : "revisar" }
 ];
}
function healthLabel(score: number, tone: PrismaMobileCommandTone): string { if (tone === "offline") return `Salud operativa parcial ${score}/100`; if (tone === "urgente") return `Salud en riesgo ${score}/100`; if (tone === "revisar") return `Salud a revisar ${score}/100`; return `Salud fuerte ${score}/100`; }
export function buildPrismaMobileHealthRadar(client: PrismaMobileClientSnapshot): PrismaMobileHealthRadar { const axes = buildAxes(client); const healthScore = average(axes.map((axis) => axis.score)); const weakest = [...axes].sort((a, b) => a.score - b.score)[0]; const strongest = [...axes].sort((a, b) => b.score - a.score)[0]; const offline = axes.some((axis) => axis.tone === "offline"); const tone = toneForScore(healthScore, offline); return { contractId: PRISMA_MOBILE_HEALTH_RADAR_CONTRACT_ID, healthScore, healthLabel: healthLabel(healthScore, tone), tone, weakestArea: weakest.label, strongestArea: strongest.label, ownerSummary: `El negocio está en ${healthScore}/100. Atiende primero ${weakest.label.toLowerCase()} y conserva ${strongest.label.toLowerCase()} como punto fuerte.`, axes, watchlist: buildWatchlist(client, axes), guardrails: ["No cerrar el día con datos en respaldo local si hay diferencias de caja.", "Validar productos críticos antes de la siguiente hora pico.", "No tomar decisiones de compra si una sucursal está offline.", "Mandar brief diario solo después de revisar la zona más débil."], nextReview: tone === "sano" ? "revisión normal de cierre" : tone === "revisar" ? "revisión antes del corte" : "revisión inmediata" }; }
