from __future__ import annotations

from pathlib import Path

DEFAULT_ROOT_DIR = Path("apps/code-atlas")
BACKUP_DIR_NAME = "_chatgpt_patch_backups"
PLUGIN_DIR_NAME = "capatch_plugins"
PLUGIN_ACTIVE_DIR_NAME = "active"
PLUGIN_TEMPLATES_DIR_NAME = "templates"
PLUGIN_DISABLED_DIR_NAME = "disabled"
PLUGIN_QUARANTINE_DIR_NAME = "quarantine"
PLUGIN_ARCHIVE_DIR_NAME = "archive"
PLUGIN_REGISTRY_NAME = "_plugin_registry.json"
PLUGIN_DISABLED_NAME = "_plugin_disabled.json"
PLUGIN_LOGS_DIR_NAME = "_logs"
PLUGIN_DEFAULT_TAIL_LINES = 80
DEFAULT_MAX_LOG_LINES = 200
DEFAULT_MAX_LOG_BYTES = 262_144
DEFAULT_MAX_ARTIFACT_FILES = 64
DEFAULT_MAX_TAIL_FILES = 32
DEFAULT_COMMAND_TIMEOUT_SECONDS = 45
DEFAULT_MAX_FIX_PROPOSALS_TO_EXECUTE = 2
DEFAULT_GIT_DIRTY_FILE_SOFT_LIMIT = 40
DEFAULT_REPORT_BUNDLE_FORMAT = "md"
DEFAULT_LINE_ENDING = "preserve"
DEFAULT_ENCODING = "utf-8"
DEFAULT_HASH_ALGORITHM = "sha256"
