from __future__ import annotations

CAPATCH_SYSTEM_TARGET_VERSION = "6.0.0"
CAPATCH_ARCH_SPEC_VERSION = "1.0.0"
CAPATCH_PLUGIN_RUNTIME_VERSION = "6.0.0"
PATCH_OPERATION_SCHEMA_VERSION = "2.0.0"
PATCH_RUN_SCHEMA_VERSION = "2.0.0"
PLUGIN_PAYLOAD_SCHEMA_VERSION = "2.0.0"
VERIFICATION_RESULT_SCHEMA_VERSION = "2.0.0"
INTERVENTION_GATE_SCHEMA_VERSION = "1.0.0"
BASELINE_SCHEMA_VERSION = "1.0.0"
