#!/usr/bin/env python3
from __future__ import annotations

import sys
import argparse
import re
from pathlib import Path

_BOOT = Path(__file__).resolve()
for _parent in (_BOOT.parent, *_BOOT.parents):
    if (_parent / "package.json").exists() and (_parent / "pnpm-workspace.yaml").exists():
        if str(_parent) not in sys.path:
            sys.path.insert(0, str(_parent))
        break

from tools.hos._core.repo_root import find_repo_root
from tools.hos._core.stable_text import write_text

NAME_PATTERN = re.compile(r"^[A-Z][A-Za-z0-9]+$")


def _component_tsx(name: str) -> str:
    return f"""import "./{name}.styles.css";
import type {{ ReactNode }} from "react";

export interface {name}Props {{
  readonly title: string;
  readonly subtitle?: string;
  readonly children?: ReactNode;
}}

export function {name}(props: {name}Props): JSX.Element {{
  const {{ title, subtitle, children }} = props;
  return (
    <section className="{name.lower()}-root" data-component="{name}">
      <header className="{name.lower()}-header">
        <h3 className="{name.lower()}-title">{{title}}</h3>
        {{subtitle ? <p className="{name.lower()}-subtitle">{{subtitle}}</p> : null}}
      </header>
      <div className="{name.lower()}-body">{{children}}</div>
    </section>
  );
}}
"""


def _component_styles(name: str) -> str:
    root = f".{name.lower()}-root"
    return f"""{root} {{
  --card-bg: var(--ui-surface-1, rgba(255, 255, 255, 0.92));
  --card-border: var(--ui-border-1, rgba(229, 233, 240, 0.75));
  --card-text: var(--ui-text-1, rgba(16, 24, 40, 1));
  --card-muted: var(--ui-text-2, rgba(71, 84, 103, 1));
  --card-radius: var(--ui-core-radius-lg, 16px);
  --card-space: var(--ui-core-space-4, 16px);
  --card-shadow: var(--ui-shadow-2, 0 18px 38px rgba(15, 23, 42, 0.09));
  --glass-overlay: linear-gradient(
    140deg,
    rgba(255, 255, 255, 0.65),
    rgba(255, 255, 255, 0.35)
  );
  position: relative;
  border-radius: var(--card-radius);
  border: 1px solid var(--card-border);
  background: var(--glass-overlay), var(--card-bg);
  backdrop-filter: blur(var(--ui-fx-blur-sm, 8px));
  box-shadow: var(--card-shadow);
  color: var(--card-text);
  padding: var(--card-space);
  overflow: hidden;
}}

.{name.lower()}-root::after {{
  content: "";
  position: absolute;
  inset: 0;
  pointer-events: none;
  background: linear-gradient(180deg, rgba(255, 255, 255, 0.28), rgba(255, 255, 255, 0));
  mix-blend-mode: soft-light;
}}

.{name.lower()}-header {{
  display: flex;
  flex-direction: column;
  gap: var(--ui-core-space-2, 8px);
}}

.{name.lower()}-title {{
  margin: 0;
  font-size: 1rem;
  line-height: 1.4;
  letter-spacing: 0.01em;
}}

.{name.lower()}-subtitle {{
  margin: 0;
  font-size: 0.875rem;
  line-height: 1.35;
  color: var(--card-muted);
}}

.{name.lower()}-body {{
  margin-top: var(--ui-core-space-3, 12px);
  display: grid;
  gap: var(--ui-core-space-3, 12px);
}}
"""


def _component_story(name: str) -> str:
    return f"""import type {{ Meta, StoryObj }} from "@storybook/react";
import {{ {name} }} from "./{name}";

const meta: Meta<typeof {name}> = {{
  title: "Generated/{name}",
  component: {name},
  args: {{
    title: "{name} Title",
    subtitle: "Generated by tools/hos/ui/scaffold_component.py"
  }}
}};

export default meta;
type Story = StoryObj<typeof {name}>;

export const Default: Story = {{
  render: (args) => (
    <{name} {{...args}}>
      <p>Replace this placeholder content with a real UI fragment.</p>
    </{name}>
  )
}};
"""


def _component_test(name: str) -> str:
    return f"""import {{ describe, expect, it }} from "vitest";
import {{ renderToString }} from "react-dom/server";
import {{ {name} }} from "./{name}";

describe("{name}", () => {{
  it("renders title and subtitle deterministically", () => {{
    const html = renderToString(
      <{name} title="A" subtitle="B">
        <span>Body</span>
      </{name}>
    );
    expect(html).toContain("A");
    expect(html).toContain("B");
    expect(html).toContain("Body");
  }});
}});
"""


def _index_file(name: str) -> str:
    return f'export * from "./{name}";\n'


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate component skeleton for UI tooling flows.")
    parser.add_argument("--name", required=True, help="Component name in PascalCase.")
    parser.add_argument(
        "--out-dir",
        default="tools/_local/ui_scaffold/components",
        help="Output parent directory.",
    )
    parser.add_argument("--force", action="store_true", help="Overwrite existing files.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not NAME_PATTERN.match(args.name):
        raise ValueError("component name must be PascalCase and start with uppercase letter")

    repo_root = find_repo_root()
    out_dir = Path(args.out_dir)
    if not out_dir.is_absolute():
        out_dir = (repo_root / out_dir).resolve()
    component_dir = out_dir / args.name

    file_map = {
        component_dir / f"{args.name}.tsx": _component_tsx(args.name),
        component_dir / f"{args.name}.styles.css": _component_styles(args.name),
        component_dir / f"{args.name}.stories.tsx": _component_story(args.name),
        component_dir / f"{args.name}.test.tsx": _component_test(args.name),
        component_dir / "index.ts": _index_file(args.name),
    }

    if component_dir.exists() and not args.force:
        raise FileExistsError(f"component directory exists: {component_dir}")

    for path in sorted(file_map):
        write_text(path, file_map[path], trailing_newline=True)
        print(f"[scaffold_component] wrote {path.as_posix()}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
