import {RELEASE_GATE_READY_COPY,RELEASE_GATE_SURFACE_LABELS,type ReleaseGateCheck,type ReleaseGateSnapshot,type ReleaseGateStatus,type ReleaseGateSurface} from "./release-gate-contract";
export type ReleaseGateBucket={surface:ReleaseGateSurface;label:string;ready:number;attention:number;blocked:number;total:number};
export type ReleaseGateViewModel={status:ReleaseGateStatus;statusLabel:string;score:number;readyCount:number;attentionCount:number;blockedCount:number;totalCount:number;buckets:ReleaseGateBucket[];checks:ReleaseGateCheck[];expectedCaptures:ReleaseGateSnapshot["expectedCaptures"];headline:string;summary:string};
const ORDER:ReleaseGateSurface[]=["venta","catalogo","turno","pendientes","exportacion","navegacion","copy","rollback"];
export function countByStatus(checks:ReleaseGateCheck[]){return checks.reduce((acc,check)=>{acc[check.status]+=1;return acc},{ready:0,attention:0,blocked:0} as Record<ReleaseGateStatus,number>)}
export function scoreReleaseGate(checks:ReleaseGateCheck[]){if(checks.length===0)return 0;const c=countByStatus(checks);return Math.round(((c.ready+c.attention*0.45)/checks.length)*100)}
export function summarizeGateBuckets(checks:ReleaseGateCheck[]):ReleaseGateBucket[]{return ORDER.map((surface)=>{const scoped=checks.filter((check)=>check.surface===surface);const c=countByStatus(scoped);return{surface,label:RELEASE_GATE_SURFACE_LABELS[surface],ready:c.ready,attention:c.attention,blocked:c.blocked,total:scoped.length}})}
export function resolveGateStatus(checks:ReleaseGateCheck[]):ReleaseGateStatus{const c=countByStatus(checks);if(c.blocked>0)return"blocked";if(c.attention>0)return"attention";return"ready"}
export function buildReleaseGateViewModel(snapshot:ReleaseGateSnapshot):ReleaseGateViewModel{const c=countByStatus(snapshot.checks);const status=resolveGateStatus(snapshot.checks);return{status,statusLabel:RELEASE_GATE_READY_COPY[status],score:scoreReleaseGate(snapshot.checks),readyCount:c.ready,attentionCount:c.attention,blockedCount:c.blocked,totalCount:snapshot.checks.length,buckets:summarizeGateBuckets(snapshot.checks),checks:snapshot.checks,expectedCaptures:snapshot.expectedCaptures,headline:status==="ready"?"Tablet lista para cierre operativo":status==="attention"?"Tablet requiere revisión menor":"Tablet bloqueada para liberar",summary:"Valida venta, catálogo, turno, pendientes, exportación, navegación, lenguaje visible y rollback de instalación."}}
